# Generated by Django 4.2.11 on 2024-04-18 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_friendship_remove_user_following_delete_connection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
