# Generated by Django 4.2.11 on 2024-04-26 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_friendship_follower_alter_friendship_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="followings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
