# Generated by Django 4.2.11 on 2024-05-06 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0002_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="tweet",
            new_name="liketweet",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="user",
            new_name="likeuser",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("likeuser", "liketweet")},
        ),
    ]
