# Generated by Django 4.2.11 on 2024-05-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0004_alter_like_liketweet"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(fields=("likeuser", "liketweet"), name="unique_like"),
        ),
    ]
