# Generated by Django 5.0.6 on 2024-05-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0005_alter_like_unique_together_like_unique_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
